### ISSUE TITLE
LifeWindow: 0 <- is this valid?

### ISSUE THREAD

**Issue by unisqu** [allegro/bigcache#104]
1. I would like to have unexpired LifeWindow but only through LRU removal. Is it possible with LifeWindow: 0,?

2. is bigcache production ready?

config := bigcache.Config {
		// number of shards (must be a power of 2)
		Shards: 1024,
		// time after which entry can be evicted
		LifeWindow: 0,
		// rps * lifeWindow, used only in initia

**Comment by mxplusb** [comment]
To answer your questions,

1. Yes.
2. Yes.

Please let us know if you have more questions. :)

**Comment by WKBae** [comment]
You should set LifeWindow to large enough value to prevent expiration.

`cacheShard.onEvict()` evicts the key immediately on next call to `cacheShard.set()` if LifeWindow is zero.

https://github.com/allegro/bigcache/blob/21e5ca5c3d539f94e8dc563350acd97c5400154f/shard.go#L246-L253


As this is fairly old issue the logic might have changed since then. This is a note for future issue-seeker like me :)
