### ISSUE TITLE
Add per entry expiration

### ISSUE THREAD

**Issue by yiiton** [allegro/bigcache#13]
Do you plan to add per entry expiration?

**Comment by druminski** [comment]
BigCache core is based on FIFO queue. With every write to bigcache the oldest entry from queue is read and its creation time is compared with expiration time. If entry is older than expiration time then it is removed from the queue. This mechanism is very simple and fast. I don't see how can we add expiration per entry without impact on performance because I assume that additional entries sorting/scanning or mapping would be required. Therefore we don't plan to add this feature, however [freecache](https://github.com/coocood/freecache) implementation is different and offers it, so I recommend to check it out.

**Comment by yiiton** [comment]
Thank you for your answer
