### ISSUE TITLE
queue new issue

### ISSUE THREAD

**Issue by zuzuviewer** [allegro/bigcache#160]
```
func NewBytesQueue(initialCapacity int, maxCapacity int, verbose bool) *BytesQueue {
	return &BytesQueue{
		array:           make([]byte, initialCapacity),
		capacity:        initialCapacity,
		maxCapacity:     maxCapacity,
		headerBuffer:    make([]byte, headerEntrySize),
		tail:            leftMarginIndex,
		head:            leftMarginIndex,
		rightMargin:     leftMarginIndex,
		verbose:         verbose,
		initialCapacity: initialCapacity,
	}
}
```
`array` and `headerBuffer` use make to initalize, but the second param of make is len, if `initialCapacity` means capactiy, it shoud be use as third param(`make([]byte,0,initialCapacity)`)

**Comment by cristaloleg** [comment]
Nice catch @zuzuviewer.

Well the problem is related only to variables names, looking down the code (https://github.com/allegro/bigcache/blob/master/queue/bytes_queue.go) we can see that there is no usage of `append` func over array.

If you think it will be better to rename `NewBytesQueue` params to something less tricky I encourage you to make a pull request 😉

**Comment by zuzuviewer** [comment]
> Nice catch @zuzuviewer.
> 
> Well the problem is related only to variables names, looking down the code (https://github.com/allegro/bigcache/blob/master/queue/bytes_queue.go) we can see that there is no usage of `append` func over array.
> 
> If you think it will be better to rename `NewBytesQueue` params to something less tricky I encourage you to make a pull request 😉

@cristaloleg ,I look this just now,so I can't pull right now.Maybe I can pull request few days later.But now I see some func use this capacity ,for example 'func (q *BytesQueue) availableSpaceAfterTail() int',I think there ensure use it as capacity
