### ISSUE TITLE
Push emptyBlobLen inside the allocateAdditionalMemory() function

### ISSUE THREAD

**Issue by junhsieh** [allegro/bigcache#29]
Hi There,

I am trying to learn how bigcache works. May I know the reason why to push "emptyBlobLen" inside the allocateAdditionalMemory() function? What is the purpose of doing that? I have also noticed the constant minimumEmptyBlobSize and its comment: **"Minimum empty blob size in bytes. Empty blob fills space between tail and head in additional memory allocation."**. However, I still could not figure it out the reason why to do that?

Thanks,

**Comment by druminski** [comment]
Hi,

There is a unit test named `TestAllocateAdditionalSpaceForInsufficientFreeFragmentedSpaceWhereTailIsBeforeHead`. It can help understand empty blob creation. On below piece of paper you can find what is going on during this test execution:

![img_1094](https://cloud.githubusercontent.com/assets/4473056/21641048/7cf929ae-d279-11e6-958b-66b7284b9d83.JPG)

As you can see in step 5a. bigger array is allocated and empty blob is created between blob `c` and `b`. Thanks this index of blob `b` does not change, so you can still read it from the same place. It was implemented in this way because you can keep references/indexes to bigcache entries outside bigcache and expect that they don't change when additional space allocation occurs.

I hope this answers on your questions.

Greetings,
Luke

**Comment by junhsieh** [comment]
@druminski Thanks for pointing me to the testing function. I have totally neglected the testing file before. After reading the codes and your detail explanation, it makes much more sense now. Thanks for your help.
